[project]
name = "usd-validation-nvidia"
dynamic = ["version"]
description = "NVIDIA Asset Validator"
authors = [
    {name = "NVIDIA"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10,<3.13"

[project.urls]
Repository = "https://github.com/NVIDIA-Omniverse/usd-validation-nvidia"
Changelog = "https://github.com/NVIDIA-Omniverse/usd-validation-nvidia/blob/main/CHANGELOG.md"

[project.optional-dependencies]
usd = ["usd-core>=22.11"]
numpy = ["numpy>=1"]

[tool.hatch.version]
path = "VERSION.md"
pattern = "^(?P<version>.+)$"

[project.scripts]
nvidia_usd_validate = "usd_validation_nvidia:cli_main"

[project.entry-points."omni.asset_validator"]
default = "usd_validation_nvidia:DefaultPlugin"

[tool.hatch.build.targets.sdist]
artifacts = [
    "src/usd_validation_nvidia/capabilities",
]

[tool.hatch.build.targets.wheel]
packages = ["src/usd_validation_nvidia", "src/omni"]

[tool.hatch.build.targets.wheel.force-include]
"src/usd_validation_nvidia/capabilities" = "usd_validation_nvidia/capabilities"

[build-system]
requires = ["hatchling"] # SWIPAT filed under: http://nvbugs/5866335
build-backend = "hatchling.build"
