[project]
name = "nvidia-usd-validation"
version = "1.18.1"
description = "NVIDIA Asset Validator"
authors = [
    {name = "NVIDIA"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10,<3.13"

[project.optional-dependencies]
usd = ["usd-core>=22.11"]
numpy = ["numpy>=1"]

[project.scripts]
nvidia_usd_validate = "nvidia_usd_validation:cli_main"

[project.entry-points."omni.asset_validator"]
default = "nvidia_usd_validation:DefaultPlugin"

[tool.hatch.build.targets.sdist]
artifacts = [
    "src/nvidia_usd_validation/capabilities",
]

[tool.hatch.build.targets.wheel]
packages = ["src/nvidia_usd_validation", "src/omni"]

[tool.hatch.build.targets.wheel.force-include]
"src/nvidia_usd_validation/capabilities" = "nvidia_usd_validation/capabilities"

[build-system]
requires = ["hatchling"] # SWIPAT filed under: http://nvbugs/5866335
build-backend = "hatchling.build"
