# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
from ._atomic_asset import (
    AnchoredAssetPathsChecker,
    SupportedFileTypesChecker,
    UsdzUdimLimitationChecker,
)
from ._basic import (
    ByteAlignmentChecker,
    CompressionChecker,
    ExtentsChecker,
    KindChecker,
    MissingReferenceChecker,
    NormalMapTextureChecker,
    PortableAssetPathChecker,
    PrimEncapsulationChecker,
    StageMetadataChecker,
    TextureChecker,
    TypeChecker,
    UsdzPackageValidator,
)
from ._gaussian_splat import GaussianSplatSchemaChecker
from ._geometry import (
    AssetOriginPositioningChecker,
    ContainsMeshChecker,
    IndexedPrimvarChecker,
    ManifoldChecker,
    NormalsExistChecker,
    NormalsValidChecker,
    NormalsWindingsChecker,
    SubdivisionSchemeChecker,
    UnusedMeshTopologyChecker,
    UnusedPrimvarChecker,
    ValidateTopologyChecker,
    WeldChecker,
    ZeroAreaFaceChecker,
)
from ._hierarchy import HierarchyHasRootChecker, RootPrimXformableChecker
from ._layers import LayerSpecChecker, UsdAsciiPerformanceChecker
from ._layout import DanglingOverPrimChecker, DefaultPrimChecker
from ._materials import (
    MaterialOldMdlSchemaChecker,
    MaterialOutOfScopeChecker,
    MaterialPathChecker,
    MaterialUsdPreviewSurfaceChecker,
    ShaderImplementationSourceChecker,
    UsdDanglingMaterialBinding,
    UsdMaterialBindingApi,
)
from ._misc import (
    SkelBindingAPIAppliedChecker,
    UsdGeomSubsetChecker,
    UsdLuxSchemaChecker,
)
from ._performance import (
    AlmostExtremeExtentChecker,
    BaseBoundsChecker,
    BoundsLimit,
    PointsPrecisionChecker,
    PointsPrecisionErrorChecker,
    PointsPrecisionWarningChecker,
    PrecisionLimit,
)
from ._physics import (
    ArticulationChecker,
    ColliderChecker,
    MassChecker,
    PhysicsJointChecker,
    RigidBodyChecker,
)
from ._unicode import UnicodeNameChecker
from ._units import UnitsInMetersChecker, UpAxisZChecker

__all__ = [
    "AlmostExtremeExtentChecker",
    "AnchoredAssetPathsChecker",
    "ArticulationChecker",
    "AssetOriginPositioningChecker",
    "BaseBoundsChecker",
    "BoundsLimit",
    "ByteAlignmentChecker",
    "ColliderChecker",
    "CompressionChecker",
    "ContainsMeshChecker",
    "DanglingOverPrimChecker",
    "DefaultPrimChecker",
    "ExtentsChecker",
    "GaussianSplatSchemaChecker",
    "HierarchyHasRootChecker",
    "IndexedPrimvarChecker",
    "KindChecker",
    "LayerSpecChecker",
    "ManifoldChecker",
    "MassChecker",
    "MaterialOldMdlSchemaChecker",
    "MaterialOutOfScopeChecker",
    "MaterialPathChecker",
    "MaterialUsdPreviewSurfaceChecker",
    "MissingReferenceChecker",
    "NormalMapTextureChecker",
    "NormalsExistChecker",
    "NormalsValidChecker",
    "NormalsWindingsChecker",
    "PhysicsJointChecker",
    "PointsPrecisionChecker",
    "PointsPrecisionErrorChecker",
    "PointsPrecisionWarningChecker",
    "PortableAssetPathChecker",
    "PrecisionLimit",
    "PrimEncapsulationChecker",
    "RigidBodyChecker",
    "RootPrimXformableChecker",
    "ShaderImplementationSourceChecker",
    "SkelBindingAPIAppliedChecker",
    "StageMetadataChecker",
    "SubdivisionSchemeChecker",
    "SupportedFileTypesChecker",
    "TextureChecker",
    "TypeChecker",
    "UnicodeNameChecker",
    "UnitsInMetersChecker",
    "UnusedMeshTopologyChecker",
    "UnusedPrimvarChecker",
    "UpAxisZChecker",
    "UsdAsciiPerformanceChecker",
    "UsdDanglingMaterialBinding",
    "UsdGeomSubsetChecker",
    "UsdLuxSchemaChecker",
    "UsdMaterialBindingApi",
    "UsdzPackageValidator",
    "UsdzUdimLimitationChecker",
    "ValidateTopologyChecker",
    "WeldChecker",
    "ZeroAreaFaceChecker",
]
